// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3CZ7TAz2WkznXv0DVIjIXTljKsOJ0a90',
    appId: '1:576821357649:web:ca7785ecd22880ddac9c70',
    messagingSenderId: '576821357649',
    projectId: 'eazyposh-c82eb',
    authDomain: 'eazyposh-c82eb.firebaseapp.com',
    storageBucket: 'eazyposh-c82eb.appspot.com',
    measurementId: 'G-BH7SFZHBEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf0EzBLE8hAgN7wGkw_LQBacq2PMUAN7I',
    appId: '1:576821357649:android:2a43eb309d1faad3ac9c70',
    messagingSenderId: '576821357649',
    projectId: 'eazyposh-c82eb',
    storageBucket: 'eazyposh-c82eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIYFoYlwf2_eZUZy6n-N8-8Ui4QnCRfNA',
    appId: '1:576821357649:ios:87cb9e95c13d2fecac9c70',
    messagingSenderId: '576821357649',
    projectId: 'eazyposh-c82eb',
    storageBucket: 'eazyposh-c82eb.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIYFoYlwf2_eZUZy6n-N8-8Ui4QnCRfNA',
    appId: '1:576821357649:ios:87cb9e95c13d2fecac9c70',
    messagingSenderId: '576821357649',
    projectId: 'eazyposh-c82eb',
    storageBucket: 'eazyposh-c82eb.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3CZ7TAz2WkznXv0DVIjIXTljKsOJ0a90',
    appId: '1:576821357649:web:da67684e9c25ea5cac9c70',
    messagingSenderId: '576821357649',
    projectId: 'eazyposh-c82eb',
    authDomain: 'eazyposh-c82eb.firebaseapp.com',
    storageBucket: 'eazyposh-c82eb.appspot.com',
    measurementId: 'G-76DBQT75Q9',
  );
}
